using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using Newtonsoft.Json;
using UnityEngine;

namespace UnityGameTranslator.Core
{
    /// <summary>
    /// Loads custom SDF fonts from JSON + PNG files generated by msdf-atlas-gen.
    /// Allows users to add support for non-Latin scripts (CJK, Devanagari, Arabic, etc.)
    /// by placing font files in the plugin's fonts/ folder.
    /// </summary>
    public static class CustomFontLoader
    {
        #region JSON Schema (msdf-atlas-gen format)

        [Serializable]
        public class MsdfAtlasData
        {
            public AtlasInfo atlas { get; set; }
            public MetricsInfo metrics { get; set; }
            public List<GlyphInfo> glyphs { get; set; }
            public List<KerningInfo> kerning { get; set; }
        }

        [Serializable]
        public class AtlasInfo
        {
            public string type { get; set; }
            public float distanceRange { get; set; }
            public float size { get; set; }
            public int width { get; set; }
            public int height { get; set; }
            public string yOrigin { get; set; } // "bottom" or "top"
        }

        [Serializable]
        public class MetricsInfo
        {
            public float emSize { get; set; }
            public float lineHeight { get; set; }
            public float ascender { get; set; }
            public float descender { get; set; }
            public float underlineY { get; set; }
            public float underlineThickness { get; set; }
        }

        [Serializable]
        public class GlyphInfo
        {
            public int unicode { get; set; }
            public float advance { get; set; }
            public BoundsInfo planeBounds { get; set; }
            public BoundsInfo atlasBounds { get; set; }
        }

        [Serializable]
        public class BoundsInfo
        {
            public float left { get; set; }
            public float bottom { get; set; }
            public float right { get; set; }
            public float top { get; set; }
        }

        [Serializable]
        public class KerningInfo
        {
            public int unicode1 { get; set; }
            public int unicode2 { get; set; }
            public float advance { get; set; }
        }

        #endregion

        #region Custom Font Info

        /// <summary>
        /// Information about a loaded custom font.
        /// </summary>
        public class CustomFontInfo
        {
            public string Name { get; set; }
            public string JsonPath { get; set; }
            public string PngPath { get; set; }
            public MsdfAtlasData AtlasData { get; set; }
            public Texture2D AtlasTexture { get; set; }
            public object FontAsset { get; set; } // TMP_FontAsset or TMProOld.TMP_FontAsset
            public bool IsLoaded { get; set; }
            public string Error { get; set; }
        }

        #endregion

        // Loaded custom fonts
        private static readonly Dictionary<string, CustomFontInfo> _customFonts = new Dictionary<string, CustomFontInfo>();

        // Cached type references for reflection
        private static Type _tmpFontAssetType;
        private static Type _tmpGlyphType;
        private static Type _tmpTextElementType;
        private static Type _faceInfoType;
        private static bool _typesInitialized;
        private static bool _useAlternateTMP;
        private static bool _existingFontDumped;

        /// <summary>
        /// Gets all available custom fonts (loaded or not).
        /// </summary>
        public static IReadOnlyDictionary<string, CustomFontInfo> CustomFonts => _customFonts;

        /// <summary>
        /// Scans the fonts folder and loads all available custom fonts.
        /// </summary>
        public static void Initialize(string pluginFolder)
        {
            var fontsFolder = Path.Combine(pluginFolder, "fonts");

            if (!Directory.Exists(fontsFolder))
            {
                TranslatorCore.LogInfo($"[CustomFontLoader] No fonts folder found at {fontsFolder}");
                return;
            }

            TranslatorCore.LogInfo($"[CustomFontLoader] Scanning fonts folder: {fontsFolder}");

            // Find all JSON files
            var jsonFiles = Directory.GetFiles(fontsFolder, "*.json");
            int loadedCount = 0;

            foreach (var jsonPath in jsonFiles)
            {
                var fileName = Path.GetFileNameWithoutExtension(jsonPath);
                var pngPath = Path.Combine(fontsFolder, fileName + ".png");

                if (!File.Exists(pngPath))
                {
                    TranslatorCore.LogWarning($"[CustomFontLoader] Missing PNG for {fileName}.json");
                    continue;
                }

                var fontInfo = new CustomFontInfo
                {
                    Name = fileName,
                    JsonPath = jsonPath,
                    PngPath = pngPath
                };

                try
                {
                    // Parse JSON
                    var jsonContent = File.ReadAllText(jsonPath);
                    fontInfo.AtlasData = JsonConvert.DeserializeObject<MsdfAtlasData>(jsonContent);

                    if (fontInfo.AtlasData?.glyphs == null || fontInfo.AtlasData.glyphs.Count == 0)
                    {
                        fontInfo.Error = "No glyphs in JSON";
                        TranslatorCore.LogWarning($"[CustomFontLoader] {fileName}: No glyphs found in JSON");
                    }
                    else
                    {
                        TranslatorCore.LogInfo($"[CustomFontLoader] Found {fileName}: {fontInfo.AtlasData.glyphs.Count} glyphs, {fontInfo.AtlasData.atlas.width}x{fontInfo.AtlasData.atlas.height} atlas");
                        loadedCount++;
                    }
                }
                catch (Exception ex)
                {
                    fontInfo.Error = $"JSON parse error: {ex.Message}";
                    TranslatorCore.LogWarning($"[CustomFontLoader] Failed to parse {fileName}.json: {ex.Message}");
                }

                _customFonts[fileName] = fontInfo;
            }

            TranslatorCore.LogInfo($"[CustomFontLoader] Found {loadedCount} custom font(s)");
        }

        /// <summary>
        /// Gets the names of all available custom fonts.
        /// </summary>
        public static string[] GetCustomFontNames()
        {
            var names = new List<string>();
            foreach (var kvp in _customFonts)
            {
                if (string.IsNullOrEmpty(kvp.Value.Error))
                    names.Add(kvp.Key);
            }
            return names.ToArray();
        }

        /// <summary>
        /// Loads a custom font's texture and creates the TMP_FontAsset.
        /// Call this lazily when the font is actually needed.
        /// </summary>
        public static object LoadCustomFont(string fontName)
        {
            if (!_customFonts.TryGetValue(fontName, out var fontInfo))
            {
                TranslatorCore.LogWarning($"[CustomFontLoader] Font not found: {fontName}");
                return null;
            }

            if (fontInfo.IsLoaded && fontInfo.FontAsset != null)
                return fontInfo.FontAsset;

            if (!string.IsNullOrEmpty(fontInfo.Error))
            {
                TranslatorCore.LogWarning($"[CustomFontLoader] Cannot load {fontName}: {fontInfo.Error}");
                return null;
            }

            try
            {
                // Load PNG texture
                var pngData = File.ReadAllBytes(fontInfo.PngPath);
                var texture = new Texture2D(2, 2, TextureFormat.RGBA32, false);
                texture.filterMode = FilterMode.Bilinear;

                if (!LoadImageToTexture(texture, pngData))
                {
                    fontInfo.Error = "Failed to load PNG";
                    TranslatorCore.LogWarning($"[CustomFontLoader] Failed to load PNG for {fontName}");
                    return null;
                }

                // For SDF fonts, the distance field is in RGB (grayscale) but TMP expects it in Alpha
                // Convert by copying R channel to Alpha
                ConvertSdfTextureForTMP(texture);

                fontInfo.AtlasTexture = texture;
                TranslatorCore.LogInfo($"[CustomFontLoader] Loaded texture: {texture.width}x{texture.height}, format: {texture.format}");

                // Debug: Check if texture has actual content (not all white/transparent)
                try
                {
                    byte[] rawSample = GetRawTextureDataSafe(texture);
                    int bpp = GetBytesPerPixel(texture.format);
                    int pixelCount = rawSample.Length / bpp;
                    int sampleSize = Math.Min(100, pixelCount);
                    int nonWhiteCount = 0;
                    for (int pi = 0; pi < sampleSize; pi++)
                    {
                        int idx = pi * bpp;
                        if (idx + bpp > rawSample.Length) break;
                        bool isWhite = true;
                        for (int b = 0; b < bpp && b < 4; b++)
                        {
                            if (rawSample[idx + b] < 252) { isWhite = false; break; }
                        }
                        if (!isWhite) nonWhiteCount++;
                    }
                    TranslatorCore.LogInfo($"[CustomFontLoader] Texture sample: {nonWhiteCount}/{sampleSize} non-white pixels");
                }
                catch (Exception ex)
                {
                    TranslatorCore.LogWarning($"[CustomFontLoader] Could not sample texture: {ex.Message}");
                }

                // Initialize type references if needed
                if (!_typesInitialized)
                    InitializeTypes();

                // Create the font asset
                fontInfo.FontAsset = CreateFontAsset(fontInfo);
                fontInfo.IsLoaded = true;

                if (fontInfo.FontAsset != null)
                {
                    TranslatorCore.LogInfo($"[CustomFontLoader] Successfully created font asset for {fontName}");
                }
                else
                {
                    fontInfo.Error = "Failed to create font asset";
                }

                return fontInfo.FontAsset;
            }
            catch (Exception ex)
            {
                fontInfo.Error = $"Load error: {ex.Message}";
                TranslatorCore.LogError($"[CustomFontLoader] Error loading {fontName}: {ex}");
                return null;
            }
        }

        /// <summary>
        /// Initializes type references for TMP classes via reflection.
        /// </summary>
        /// <summary>
        /// FindObjectsOfTypeAll compatible with IL2CPP.
        /// On IL2CPP, Resources.FindObjectsOfTypeAll(Type) may have different signature.
        /// </summary>
        private static UnityEngine.Object[] FindObjectsOfTypeAllSafe(Type type)
        {
            if (type == null) return new UnityEngine.Object[0];

            // Try direct call
            try
            {
                return Resources.FindObjectsOfTypeAll(type);
            }
            catch { }

            // IL2CPP: try via reflection on the actual Resources type
            try
            {
                var resourcesType = typeof(Resources);
                foreach (var method in resourcesType.GetMethods(BindingFlags.Public | BindingFlags.Static))
                {
                    if (method.Name != "FindObjectsOfTypeAll") continue;
                    var parameters = method.GetParameters();
                    if (parameters.Length != 1) continue;

                    // Accept any single-parameter overload
                    try
                    {
                        object arg = type;
                        // If the parameter expects an IL2CPP Type, we may need to convert
                        var paramType = parameters[0].ParameterType;
                        if (paramType == typeof(Type) || paramType.IsAssignableFrom(typeof(Type)))
                        {
                            var result = method.Invoke(null, new object[] { type });
                            if (result is UnityEngine.Object[] array) return array;

                            // IL2CPP may return Il2CppReferenceArray
                            if (result != null)
                            {
                                var list = new List<UnityEngine.Object>();
                                if (result is System.Collections.IEnumerable enumerable)
                                {
                                    foreach (var item in enumerable)
                                    {
                                        if (item is UnityEngine.Object uobj)
                                            list.Add(uobj);
                                    }
                                }
                                if (list.Count > 0) return list.ToArray();
                            }
                        }
                    }
                    catch { continue; }
                }
            }
            catch { }

            return new UnityEngine.Object[0];
        }

        /// <summary>
        /// ScriptableObject.CreateInstance compatible with IL2CPP.
        /// On IL2CPP, the Type parameter may need to be an IL2CPP Type wrapper.
        /// </summary>
        private static UnityEngine.Object CreateScriptableObjectSafe(Type type)
        {
            // Try direct call first
            try
            {
                return ScriptableObject.CreateInstance(type);
            }
            catch { }

            // IL2CPP: try via reflection
            try
            {
                var soType = typeof(ScriptableObject);
                foreach (var method in soType.GetMethods(BindingFlags.Public | BindingFlags.Static))
                {
                    if (method.Name != "CreateInstance") continue;
                    if (method.IsGenericMethod) continue;
                    var parameters = method.GetParameters();
                    if (parameters.Length != 1) continue;

                    try
                    {
                        var result = method.Invoke(null, new object[] { type });
                        if (result is UnityEngine.Object uobj)
                            return uobj;
                    }
                    catch { continue; }
                }

                // Try generic version: ScriptableObject.CreateInstance<T>()
                var genericMethod = soType.GetMethod("CreateInstance", BindingFlags.Public | BindingFlags.Static, null, Type.EmptyTypes, null);
                if (genericMethod != null && genericMethod.IsGenericMethodDefinition)
                {
                    var specific = genericMethod.MakeGenericMethod(type);
                    var result = specific.Invoke(null, null);
                    if (result is UnityEngine.Object uobj)
                        return uobj;
                }
            }
            catch (Exception ex)
            {
                TranslatorCore.LogWarning($"[CustomFontLoader] CreateInstance reflection failed: {ex.Message}");
            }

            // Last resort: try Activator.CreateInstance
            try
            {
                var obj = Activator.CreateInstance(type);
                if (obj is UnityEngine.Object uobj)
                    return uobj;
            }
            catch { }

            TranslatorCore.LogWarning($"[CustomFontLoader] Cannot create ScriptableObject of type {type.Name}");
            return null;
        }

        /// <summary>
        /// Find a type by simple name in an assembly (handles IL2CPP prefixed namespaces).
        /// </summary>
        private static Type FindTypeByName(System.Reflection.Assembly asm, string typeName)
        {
            try
            {
                foreach (var type in asm.GetTypes())
                {
                    if (type.Name == typeName)
                        return type;
                }
            }
            catch { }
            return null;
        }

        private static void InitializeTypes()
        {
            _typesInitialized = true;

            // Use TypeHelper's already-resolved TMP_FontAsset type (handles IL2CPP namespaces like Il2CppTMPro)
            if (TypeHelper.TMP_FontAssetType != null)
            {
                _tmpFontAssetType = TypeHelper.TMP_FontAssetType;
                _useAlternateTMP = TypeHelper.UseAlternateTMP;

                // Find related types in the same assembly
                var asm = _tmpFontAssetType.Assembly;
                string ns = _tmpFontAssetType.Namespace ?? "";

                // Try exact namespace first, then scan by name
                _tmpGlyphType = asm.GetType(ns + ".TMP_Glyph") ?? FindTypeByName(asm, "TMP_Glyph");
                _tmpTextElementType = asm.GetType(ns + ".TMP_TextElement") ?? FindTypeByName(asm, "TMP_TextElement");
                _faceInfoType = asm.GetType(ns + ".FaceInfo") ?? FindTypeByName(asm, "FaceInfo");

                TranslatorCore.LogInfo($"[CustomFontLoader] Using TypeHelper-resolved types from {asm.GetName().Name} (ns={ns})");
                TranslatorCore.LogInfo($"[CustomFontLoader] FontAsset={_tmpFontAssetType.Name}, Glyph={_tmpGlyphType?.Name ?? "null"}, FaceInfo={_faceInfoType?.Name ?? "null"}");
            }
            else
            {
                // Fallback: manual scan (pre-TypeHelper or if TypeHelper failed)
                foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
                {
                    var oldFontAsset = asm.GetType("TMProOld.TMP_FontAsset");
                    if (oldFontAsset != null)
                    {
                        _tmpFontAssetType = oldFontAsset;
                        _tmpGlyphType = asm.GetType("TMProOld.TMP_Glyph");
                        _tmpTextElementType = asm.GetType("TMProOld.TMP_TextElement");
                        _faceInfoType = asm.GetType("TMProOld.FaceInfo");
                        _useAlternateTMP = true;
                        TranslatorCore.LogInfo("[CustomFontLoader] Using TMProOld types (fallback)");
                        return;
                    }

                    var stdFontAsset = asm.GetType("TMPro.TMP_FontAsset");
                    if (stdFontAsset != null && _tmpFontAssetType == null)
                    {
                        _tmpFontAssetType = stdFontAsset;
                        _tmpGlyphType = asm.GetType("TMPro.TMP_Glyph");
                        _tmpTextElementType = asm.GetType("TMPro.TMP_TextElement");
                        _faceInfoType = asm.GetType("TMPro.FaceInfo");
                        _useAlternateTMP = false;
                    }
                }
            }

            if (_tmpFontAssetType != null)
            {
                TranslatorCore.LogInfo($"[CustomFontLoader] Using {(_useAlternateTMP ? "TMProOld" : _tmpFontAssetType.Namespace)} types");
            }
            else
            {
                TranslatorCore.LogWarning("[CustomFontLoader] No TMP types found!");
            }
        }

        /// <summary>
        /// Creates a TMP_FontAsset from the loaded custom font data.
        /// </summary>
        private static object CreateFontAsset(CustomFontInfo fontInfo)
        {
            if (_tmpFontAssetType == null)
            {
                TranslatorCore.LogWarning("[CustomFontLoader] TMP_FontAsset type not found");
                return null;
            }

            try
            {
                // Try to clone an existing font asset first (better initialization)
                object fontAsset = null;
                var existingFonts = FindObjectsOfTypeAllSafe(_tmpFontAssetType);
                foreach (var existingFont in existingFonts)
                {
                    if (existingFont != null && existingFont.name != "NotoSansDevanagari" && existingFont.name != "KrutiDev714Normal")
                    {
                        // Clone the existing font
                        fontAsset = UnityEngine.Object.Instantiate(existingFont);
                        ((UnityEngine.Object)fontAsset).name = fontInfo.Name;
                        TranslatorCore.LogInfo($"[CustomFontLoader] Cloned existing font: {existingFont.name}");
                        break;
                    }
                }

                // Fallback to creating new instance if no font to clone
                if (fontAsset == null)
                {
                    fontAsset = CreateScriptableObjectSafe(_tmpFontAssetType);
                    ((UnityEngine.Object)fontAsset).name = fontInfo.Name;
                    TranslatorCore.LogInfo("[CustomFontLoader] Created new font asset instance");
                }

                var atlas = fontInfo.AtlasData.atlas;
                var metrics = fontInfo.AtlasData.metrics;
                var pointSize = atlas.size;

                // Set atlas texture
                var atlasField = _tmpFontAssetType.GetField("atlas", BindingFlags.Public | BindingFlags.Instance);
                if (atlasField != null)
                {
                    atlasField.SetValue(fontAsset, fontInfo.AtlasTexture);
                }

                // Set material (required for rendering)
                SetupMaterial(fontAsset, fontInfo.AtlasTexture, fontInfo.AtlasData.atlas.distanceRange);

                // Set face info / font info
                SetupFaceInfo(fontAsset, fontInfo, pointSize);

                // Set glyphs
                SetupGlyphs(fontAsset, fontInfo, pointSize);

                return fontAsset;
            }
            catch (Exception ex)
            {
                TranslatorCore.LogError($"[CustomFontLoader] Failed to create font asset: {ex}");
                return null;
            }
        }

        /// <summary>
        /// Dumps the structure of an existing font for debugging.
        /// </summary>
        private static void DumpExistingFontStructure(UnityEngine.Object existingFont)
        {
            try
            {
                // Skip our own custom fonts
                if (existingFont.name == "NotoSansDevanagari" || existingFont.name == "KrutiDev714Normal")
                    return;

                TranslatorCore.LogInfo($"[CustomFontLoader] === Dumping existing font: {existingFont.name} ===");

                var type = existingFont.GetType();

                // List all fields
                var allFields = type.GetFields(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
                TranslatorCore.LogInfo($"[CustomFontLoader] All fields: {string.Join(", ", allFields.Select(f => f.Name))}");

                // Find any field containing "glyph" (case insensitive)
                foreach (var field in allFields)
                {
                    if (field.Name.ToLower().Contains("glyph") || field.Name.ToLower().Contains("character"))
                    {
                        var value = field.GetValue(existingFont);
                        if (value != null)
                        {
                            var valType = value.GetType();
                            if (valType.IsGenericType && valType.GetGenericTypeDefinition() == typeof(List<>))
                            {
                                var countProp = valType.GetProperty("Count");
                                int count = (int)countProp.GetValue(value);
                                TranslatorCore.LogInfo($"[CustomFontLoader] {field.Name}: List with {count} items");

                                // Dump first few items
                                if (count > 0)
                                {
                                    var indexer = valType.GetProperty("Item");
                                    for (int i = 0; i < Math.Min(2, count); i++)
                                    {
                                        var item = indexer.GetValue(value, new object[] { i });
                                        if (item != null)
                                        {
                                            var itemType = item.GetType();
                                            var itemFields = itemType.GetFields(BindingFlags.Public | BindingFlags.Instance);
                                            var fieldValues = itemFields.Select(f => $"{f.Name}={f.GetValue(item)}");
                                            TranslatorCore.LogInfo($"[CustomFontLoader]   [{i}]: {string.Join(", ", fieldValues)}");
                                        }
                                    }
                                }
                            }
                            else if (valType.IsGenericType && valType.GetGenericTypeDefinition() == typeof(Dictionary<,>))
                            {
                                var countProp = valType.GetProperty("Count");
                                int count = (int)countProp.GetValue(value);
                                TranslatorCore.LogInfo($"[CustomFontLoader] {field.Name}: Dictionary with {count} items");
                            }
                            else
                            {
                                TranslatorCore.LogInfo($"[CustomFontLoader] {field.Name}: {valType.Name}");
                            }
                        }
                    }
                }

                // Check for atlas field
                var atlasField = type.GetField("atlas", BindingFlags.Public | BindingFlags.Instance);
                if (atlasField != null)
                {
                    var atlas = atlasField.GetValue(existingFont) as Texture2D;
                    TranslatorCore.LogInfo($"[CustomFontLoader] atlas: {(atlas != null ? $"{atlas.width}x{atlas.height}" : "NULL")}");
                }

                // Check m_fontInfo
                var fontInfoField = type.GetField("m_fontInfo", BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
                if (fontInfoField != null)
                {
                    var fontInfo = fontInfoField.GetValue(existingFont);
                    if (fontInfo != null)
                    {
                        var fiType = fontInfo.GetType();
                        var fiFields = fiType.GetFields(BindingFlags.Public | BindingFlags.Instance);
                        var fiValues = fiFields.Select(f => $"{f.Name}={f.GetValue(fontInfo)}");
                        TranslatorCore.LogInfo($"[CustomFontLoader] m_fontInfo: {string.Join(", ", fiValues)}");
                    }
                }

                TranslatorCore.LogInfo("[CustomFontLoader] === End dump ===");
                _existingFontDumped = true;
            }
            catch (Exception ex)
            {
                TranslatorCore.LogWarning($"[CustomFontLoader] Failed to dump font structure: {ex.Message}");
            }
        }

        /// <summary>
        /// Sets up the material for the font asset by copying from an existing game font.
        /// </summary>
        private static void SetupMaterial(object fontAsset, Texture2D atlas, float distanceRange)
        {
            try
            {
                Material material = null;

                // First, try to find an existing TMP font and copy its material/shader
                if (_tmpFontAssetType != null)
                {
                    var existingFonts = FindObjectsOfTypeAllSafe(_tmpFontAssetType);

                    // Debug: dump structure of first existing font (not our custom ones)
                    if (!_existingFontDumped)
                    {
                        foreach (var font in existingFonts)
                        {
                            if (font != null && font.name != "NotoSansDevanagari" && font.name != "KrutiDev714Normal")
                            {
                                DumpExistingFontStructure(font);
                                break;
                            }
                        }
                    }

                    foreach (var existingFont in existingFonts)
                    {
                        if (existingFont == null) continue;

                        // Get material from existing font
                        var matField = _tmpFontAssetType.GetField("material", BindingFlags.Public | BindingFlags.Instance);
                        var matProp = _tmpFontAssetType.GetProperty("material", BindingFlags.Public | BindingFlags.Instance);

                        Material existingMat = null;
                        if (matField != null)
                            existingMat = matField.GetValue(existingFont) as Material;
                        else if (matProp != null)
                            existingMat = matProp.GetValue(existingFont) as Material;

                        if (existingMat != null && existingMat.shader != null)
                        {
                            // Copy the material with our atlas texture
                            material = new Material(existingMat.shader);
                            material.CopyPropertiesFromMaterial(existingMat);
                            material.name = $"{((ScriptableObject)fontAsset).name} Material";
                            material.SetTexture("_MainTex", atlas);

                            // Update texture dimensions for our atlas
                            material.SetFloat("_TextureWidth", atlas.width);
                            material.SetFloat("_TextureHeight", atlas.height);

                            // GradientScale should match the SDF distanceRange from msdf-atlas-gen
                            // This controls the edge softness of the rendered text
                            material.SetFloat("_GradientScale", distanceRange);

                            TranslatorCore.LogInfo($"[CustomFontLoader] Copied material from existing font, shader: {existingMat.shader.name}");
                            TranslatorCore.LogInfo($"[CustomFontLoader] Set _TextureWidth={atlas.width}, _TextureHeight={atlas.height}, _GradientScale={distanceRange}");
                            break;
                        }
                    }
                }

                // Fallback: try to find shader directly
                if (material == null)
                {
                    string[] shaderNames = {
                        "TextMeshPro/Distance Field",
                        "TMPro/Distance Field",
                        "TextMeshPro/Mobile/Distance Field",
                        "TMPro/Mobile/Distance Field"
                    };

                    Shader shader = null;
                    foreach (var name in shaderNames)
                    {
                        shader = Shader.Find(name);
                        if (shader != null)
                        {
                            TranslatorCore.LogInfo($"[CustomFontLoader] Found shader: {name}");
                            break;
                        }
                    }

                    if (shader != null)
                    {
                        material = new Material(shader);
                        material.name = $"{((ScriptableObject)fontAsset).name} Material";
                        material.SetTexture("_MainTex", atlas);
                        material.SetFloat("_TextureWidth", atlas.width);
                        material.SetFloat("_TextureHeight", atlas.height);
                        material.SetFloat("_GradientScale", distanceRange);
                    }
                    else
                    {
                        TranslatorCore.LogWarning("[CustomFontLoader] No TMP shader found!");
                        return;
                    }
                }

                // Set material on font asset
                var materialField = _tmpFontAssetType.GetField("material", BindingFlags.Public | BindingFlags.Instance);
                if (materialField != null)
                {
                    materialField.SetValue(fontAsset, material);
                }
                else
                {
                    var materialProp = _tmpFontAssetType.GetProperty("material", BindingFlags.Public | BindingFlags.Instance);
                    if (materialProp != null && materialProp.CanWrite)
                    {
                        materialProp.SetValue(fontAsset, material);
                    }
                }

                // Debug: verify texture is set on material
                var mainTex = material.GetTexture("_MainTex");
                TranslatorCore.LogInfo($"[CustomFontLoader] Material _MainTex: {(mainTex != null ? $"{mainTex.width}x{mainTex.height}" : "NULL")}");
            }
            catch (Exception ex)
            {
                TranslatorCore.LogWarning($"[CustomFontLoader] Failed to setup material: {ex.Message}");
            }
        }

        /// <summary>
        /// Sets up the face info (font metrics).
        /// </summary>
        private static void SetupFaceInfo(object fontAsset, CustomFontInfo fontInfo, float pointSize)
        {
            var metrics = fontInfo.AtlasData.metrics;
            var atlas = fontInfo.AtlasData.atlas;

            try
            {
                // Find m_fontInfo field
                var fontInfoField = _tmpFontAssetType.GetField("m_fontInfo", BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
                if (fontInfoField == null)
                {
                    TranslatorCore.LogWarning("[CustomFontLoader] m_fontInfo field not found");
                    return;
                }

                object faceInfo;

                // Create FaceInfo instance
                if (_faceInfoType != null && _faceInfoType.IsValueType)
                {
                    // Struct - create via Activator
                    faceInfo = Activator.CreateInstance(_faceInfoType);
                }
                else if (_faceInfoType != null)
                {
                    // Class - create instance
                    faceInfo = Activator.CreateInstance(_faceInfoType);
                }
                else
                {
                    TranslatorCore.LogWarning("[CustomFontLoader] FaceInfo type not found");
                    return;
                }

                // Set fields using reflection (names may vary between TMP versions)
                float ascender = metrics.ascender * pointSize;
                float descender = metrics.descender * pointSize;
                float capHeight = ascender * 0.8f; // Approximate cap height

                SetFieldValue(faceInfo, "Name", fontInfo.Name);
                SetFieldValue(faceInfo, "PointSize", pointSize);
                SetFieldValue(faceInfo, "Scale", 1f);
                SetFieldValue(faceInfo, "CharacterCount", fontInfo.AtlasData.glyphs.Count);
                SetFieldValue(faceInfo, "LineHeight", metrics.lineHeight * pointSize);
                SetFieldValue(faceInfo, "Baseline", 0f); // Baseline is reference point, typically 0
                SetFieldValue(faceInfo, "Ascender", ascender);
                SetFieldValue(faceInfo, "CapHeight", capHeight);
                SetFieldValue(faceInfo, "Descender", descender);
                SetFieldValue(faceInfo, "CenterLine", (ascender + descender) / 2f);
                SetFieldValue(faceInfo, "SuperscriptOffset", ascender);
                SetFieldValue(faceInfo, "SubscriptOffset", descender * 0.5f);
                SetFieldValue(faceInfo, "SubSize", 0.5f);
                SetFieldValue(faceInfo, "Underline", (metrics.underlineY != 0 ? metrics.underlineY : -0.1f) * pointSize);
                SetFieldValue(faceInfo, "UnderlineThickness", (metrics.underlineThickness != 0 ? metrics.underlineThickness : 0.05f) * pointSize);
                SetFieldValue(faceInfo, "TabWidth", pointSize * 4f); // 4 spaces typically
                SetFieldValue(faceInfo, "Padding", atlas.distanceRange);
                SetFieldValue(faceInfo, "AtlasWidth", (float)atlas.width);
                SetFieldValue(faceInfo, "AtlasHeight", (float)atlas.height);

                fontInfoField.SetValue(fontAsset, faceInfo);

                // Log the configured metrics for debugging
                TranslatorCore.LogInfo($"[CustomFontLoader] Configured FaceInfo: PointSize={pointSize}, Ascender={ascender:F2}, Descender={descender:F2}, LineHeight={metrics.lineHeight * pointSize:F2}");
                TranslatorCore.LogInfo($"[CustomFontLoader] Atlas dimensions: {atlas.width}x{atlas.height}, DistanceRange={atlas.distanceRange}");

                // DEBUG: Verify the values were actually written
                var verifyFaceInfo = fontInfoField.GetValue(fontAsset);
                if (verifyFaceInfo != null)
                {
                    var verifyType = verifyFaceInfo.GetType();
                    var atlasWField = verifyType.GetField("AtlasWidth", BindingFlags.Public | BindingFlags.Instance);
                    var atlasHField = verifyType.GetField("AtlasHeight", BindingFlags.Public | BindingFlags.Instance);
                    var pointSizeField = verifyType.GetField("PointSize", BindingFlags.Public | BindingFlags.Instance);

                    float? verifyW = atlasWField?.GetValue(verifyFaceInfo) as float?;
                    float? verifyH = atlasHField?.GetValue(verifyFaceInfo) as float?;
                    float? verifyPS = pointSizeField?.GetValue(verifyFaceInfo) as float?;

                    TranslatorCore.LogInfo($"[CustomFontLoader] VERIFY m_fontInfo: AtlasWidth={verifyW}, AtlasHeight={verifyH}, PointSize={verifyPS}");
                }
            }
            catch (Exception ex)
            {
                TranslatorCore.LogWarning($"[CustomFontLoader] Failed to setup face info: {ex.Message}");
            }
        }

        /// <summary>
        /// Sets up the glyph list.
        /// </summary>
        private static void SetupGlyphs(object fontAsset, CustomFontInfo fontInfo, float pointSize)
        {
            var atlas = fontInfo.AtlasData.atlas;
            var glyphs = fontInfo.AtlasData.glyphs;
            bool yFlipped = atlas.yOrigin == "bottom";

            try
            {
                // Find glyph list field
                var glyphListField = _tmpFontAssetType.GetField("m_glyphInfoList", BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
                if (glyphListField == null)
                {
                    TranslatorCore.LogWarning("[CustomFontLoader] m_glyphInfoList field not found");
                    return;
                }

                // Create list of glyphs
                var glyphListType = typeof(List<>).MakeGenericType(_tmpGlyphType ?? _tmpTextElementType ?? typeof(object));
                var glyphList = Activator.CreateInstance(glyphListType);
                var addMethod = glyphListType.GetMethod("Add");

                foreach (var glyphInfo in glyphs)
                {
                    // Create glyph even for characters without visual bounds (like space)
                    // They still need an entry with xAdvance for proper spacing
                    var glyph = CreateGlyph(glyphInfo, atlas, pointSize, yFlipped);
                    if (glyph != null)
                    {
                        addMethod.Invoke(glyphList, new[] { glyph });
                    }
                }

                glyphListField.SetValue(fontAsset, glyphList);

                // Also build the character dictionary for lookups
                BuildCharacterDictionary(fontAsset, glyphList);

                TranslatorCore.LogInfo($"[CustomFontLoader] Added {glyphs.Count} glyphs");
            }
            catch (Exception ex)
            {
                TranslatorCore.LogWarning($"[CustomFontLoader] Failed to setup glyphs: {ex.Message}");
            }
        }

        private static bool _glyphFieldsLogged = false;

        /// <summary>
        /// Creates a single glyph object.
        /// </summary>
        private static object CreateGlyph(GlyphInfo glyphInfo, AtlasInfo atlas, float pointSize, bool yFlipped)
        {
            try
            {
                var glyphType = _tmpGlyphType ?? _tmpTextElementType;
                if (glyphType == null)
                    return null;

                // Log available fields once for debugging
                if (!_glyphFieldsLogged)
                {
                    _glyphFieldsLogged = true;
                    var fields = glyphType.GetFields(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
                    TranslatorCore.LogInfo($"[CustomFontLoader] Glyph type: {glyphType.FullName}, fields: {string.Join(", ", fields.Select(f => f.Name + ":" + f.FieldType.Name))}");
                }

                var glyph = Activator.CreateInstance(glyphType);

                var ab = glyphInfo.atlasBounds;
                var pb = glyphInfo.planeBounds;

                // Calculate atlas coordinates
                // For characters without visual bounds (like space), use zero dimensions
                float x = 0, y = 0, width = 0, height = 0;

                if (ab != null)
                {
                    // Shrink the region slightly to avoid sampling adjacent glyphs
                    float shrink = atlas.distanceRange * 0.82f;

                    x = ab.left + shrink;
                    // yFlipped (yOrigin="bottom") means we need to flip Y for TMP's coordinate system
                    y = yFlipped ? (atlas.height - ab.top + shrink) : (ab.top + shrink);
                    width = Math.Max(1, ab.right - ab.left - shrink * 2);
                    height = Math.Max(1, ab.top - ab.bottom - shrink * 2);
                }

                // Calculate offsets (planeBounds are in em units, multiply by pointSize)
                float xOffset = (pb?.left ?? 0) * pointSize;
                float yOffset = (pb?.top ?? 0) * pointSize;
                float xAdvance = glyphInfo.advance * pointSize;

                // Set glyph properties
                SetFieldValue(glyph, "id", glyphInfo.unicode);
                SetFieldValue(glyph, "x", x);
                SetFieldValue(glyph, "y", y);
                SetFieldValue(glyph, "width", width);
                SetFieldValue(glyph, "height", height);
                SetFieldValue(glyph, "xOffset", xOffset);
                SetFieldValue(glyph, "yOffset", yOffset);
                SetFieldValue(glyph, "xAdvance", xAdvance);
                SetFieldValue(glyph, "scale", 1f);

                // Log first few glyphs for debugging (Latin A-C and first Devanagari)
                bool shouldLog = (glyphInfo.unicode >= 65 && glyphInfo.unicode <= 67) // A, B, C
                    || (glyphInfo.unicode >= 2309 && glyphInfo.unicode <= 2315); // First Devanagari consonants
                if (shouldLog)
                {
                    TranslatorCore.LogInfo($"[CustomFontLoader] Glyph U+{glyphInfo.unicode:X4}: x={x}, y={y}, w={width}, h={height}, xOff={xOffset}, yOff={yOffset}, xAdv={xAdvance}");
                }

                return glyph;
            }
            catch (Exception ex)
            {
                TranslatorCore.LogWarning($"[CustomFontLoader] Failed to create glyph {glyphInfo.unicode}: {ex.Message}");
                return null;
            }
        }

        /// <summary>
        /// Builds the character dictionary for fast lookups.
        /// </summary>
        private static void BuildCharacterDictionary(object fontAsset, object glyphList)
        {
            try
            {
                var dictField = _tmpFontAssetType.GetField("m_characterDictionary", BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
                if (dictField == null)
                    return;

                var glyphType = _tmpGlyphType ?? _tmpTextElementType;
                var dictType = typeof(Dictionary<,>).MakeGenericType(typeof(int), glyphType);
                var dict = Activator.CreateInstance(dictType);
                var dictAdd = dictType.GetMethod("Add");

                var listType = glyphList.GetType();
                var countProp = listType.GetProperty("Count");
                var indexer = listType.GetProperty("Item");

                int count = (int)countProp.GetValue(glyphList);
                for (int i = 0; i < count; i++)
                {
                    var glyph = indexer.GetValue(glyphList, new object[] { i });
                    var idField = glyphType.GetField("id", BindingFlags.Public | BindingFlags.Instance);
                    if (idField != null)
                    {
                        int id = (int)idField.GetValue(glyph);
                        try
                        {
                            dictAdd.Invoke(dict, new object[] { id, glyph });
                        }
                        catch { } // Ignore duplicates
                    }
                }

                dictField.SetValue(fontAsset, dict);

                // Log dictionary size for debugging
                var dictCount = dictType.GetProperty("Count");
                int dictSize = (int)dictCount.GetValue(dict);
                TranslatorCore.LogInfo($"[CustomFontLoader] Built character dictionary with {dictSize} entries");
            }
            catch (Exception ex)
            {
                TranslatorCore.LogWarning($"[CustomFontLoader] Failed to build character dictionary: {ex.Message}");
            }
        }

        /// <summary>
        /// Helper to set a field value via reflection.
        /// </summary>
        private static void SetFieldValue(object obj, string fieldName, object value)
        {
            if (obj == null) return;

            var type = obj.GetType();
            var field = type.GetField(fieldName, BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
            if (field != null)
            {
                try
                {
                    // Convert value if needed
                    if (value != null && field.FieldType != value.GetType())
                    {
                        value = Convert.ChangeType(value, field.FieldType);
                    }
                    field.SetValue(obj, value);
                }
                catch { }
            }
        }

        // Cached LoadImage method
        private static MethodInfo _loadImageMethod;
        private static bool _loadImageMethodSearched;

        /// <summary>
        /// Loads image data into a Texture2D using reflection to call ImageConversion.LoadImage.
        /// This avoids compile-time dependency on ImageConversionModule.
        /// </summary>
        private static bool LoadImageToTexture(Texture2D texture, byte[] data)
        {
            if (texture == null || data == null || data.Length == 0)
                return false;

            // Find the LoadImage method once
            if (!_loadImageMethodSearched)
            {
                _loadImageMethodSearched = true;
                FindLoadImageMethod();
            }

            if (_loadImageMethod == null)
                return false;

            try
            {
                // Convert byte[] to the expected parameter type if needed (IL2CPP)
                object dataArg = ConvertByteArrayForMethod(_loadImageMethod, data);

                object result;
                if (_loadImageMethod.IsStatic)
                {
                    result = _loadImageMethod.Invoke(null, new object[] { texture, dataArg });
                }
                else
                {
                    result = _loadImageMethod.Invoke(texture, new object[] { dataArg });
                }

                return result is bool b && b;
            }
            catch (Exception ex)
            {
                TranslatorCore.LogWarning($"[CustomFontLoader] LoadImage failed: {ex.Message}");
                return false;
            }
        }

        /// <summary>
        /// Find the LoadImage method, handling IL2CPP where parameter types differ.
        /// On IL2CPP, byte[] parameters become Il2CppStructArray&lt;byte&gt;.
        /// </summary>
        private static void FindLoadImageMethod()
        {
            // Strategy: search by name, accept any overload with 2 params (static) or 1 param (instance)
            // that has a byte-array-like second/first parameter

            // Try ImageConversion.LoadImage first (newer Unity)
            foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
            {
                var imageConvType = asm.GetType("UnityEngine.ImageConversion");
                if (imageConvType == null) continue;

                foreach (var method in imageConvType.GetMethods(BindingFlags.Public | BindingFlags.Static))
                {
                    if (method.Name != "LoadImage") continue;
                    var parameters = method.GetParameters();
                    // Looking for LoadImage(Texture2D, byte[]) — 2 params, second is byte-array-like
                    if (parameters.Length == 2 && IsTextureType(parameters[0].ParameterType) && IsByteArrayType(parameters[1].ParameterType))
                    {
                        _loadImageMethod = method;
                        TranslatorCore.LogInfo($"[CustomFontLoader] Found ImageConversion.LoadImage({parameters[0].ParameterType.Name}, {parameters[1].ParameterType.Name})");
                        return;
                    }
                }
            }

            // Try Texture2D.LoadImage(byte[]) (older Unity or instance method)
            var texType = typeof(Texture2D);
            // On IL2CPP, the actual runtime type may be different
            foreach (var method in texType.GetMethods(BindingFlags.Public | BindingFlags.Instance))
            {
                if (method.Name != "LoadImage") continue;
                var parameters = method.GetParameters();
                if (parameters.Length == 1 && IsByteArrayType(parameters[0].ParameterType))
                {
                    _loadImageMethod = method;
                    TranslatorCore.LogInfo($"[CustomFontLoader] Found Texture2D.LoadImage({parameters[0].ParameterType.Name})");
                    return;
                }
            }

            TranslatorCore.LogWarning("[CustomFontLoader] No LoadImage method found");
        }

        /// <summary>
        /// Check if a type is a Texture2D or IL2CPP equivalent.
        /// </summary>
        private static bool IsTextureType(Type type)
        {
            return typeof(Texture2D).IsAssignableFrom(type) || type.Name.Contains("Texture2D");
        }

        /// <summary>
        /// Check if a type is byte[] or an IL2CPP byte array equivalent.
        /// </summary>
        private static bool IsByteArrayType(Type type)
        {
            if (type == typeof(byte[])) return true;
            // IL2CPP: Il2CppStructArray<byte>, Il2CppInterop.Runtime.InteropTypes.Arrays.Il2CppStructArray`1[System.Byte]
            if (type.Name.Contains("Array") && type.FullName != null && type.FullName.Contains("Byte")) return true;
            return false;
        }

        /// <summary>
        /// Convert a byte[] to the type expected by the method parameter (handles IL2CPP array types).
        /// </summary>
        private static object ConvertByteArrayForMethod(MethodInfo method, byte[] data)
        {
            var parameters = method.GetParameters();
            // Find the byte-array parameter
            Type expectedType = null;
            foreach (var param in parameters)
            {
                if (IsByteArrayType(param.ParameterType))
                {
                    expectedType = param.ParameterType;
                    break;
                }
            }

            if (expectedType == null || expectedType == typeof(byte[]))
                return data; // Direct byte[] works

            // Need to convert to IL2CPP array type
            try
            {
                // Try constructor that accepts byte[]
                var ctor = expectedType.GetConstructor(new Type[] { typeof(byte[]) });
                if (ctor != null)
                {
                    return ctor.Invoke(new object[] { data });
                }

                // Try constructor(int) + indexer copy
                ctor = expectedType.GetConstructor(new Type[] { typeof(int) });
                if (ctor != null)
                {
                    var il2cppArray = ctor.Invoke(new object[] { data.Length });
                    var indexer = expectedType.GetProperty("Item");
                    if (indexer != null)
                    {
                        for (int i = 0; i < data.Length; i++)
                            indexer.SetValue(il2cppArray, data[i], new object[] { i });
                        return il2cppArray;
                    }
                }

                TranslatorCore.LogWarning($"[CustomFontLoader] Cannot convert byte[] to {expectedType.Name}");
            }
            catch (Exception ex)
            {
                TranslatorCore.LogWarning($"[CustomFontLoader] byte[] conversion failed: {ex.Message}");
            }

            return data; // Fallback, may fail
        }

        /// <summary>
        /// Converts an SDF texture for TMP compatibility.
        /// msdf-atlas-gen outputs SDF as grayscale in RGB channels, but TMP reads distance from Alpha channel.
        /// This method copies the R channel to Alpha to make the texture compatible with TMP shaders.
        /// </summary>
        private static void ConvertSdfTextureForTMP(Texture2D texture)
        {
            if (texture == null) return;

            try
            {
                // Use reflection-safe GetRawTextureData for IL2CPP compatibility
                // On IL2CPP, the method returns Il2CppStructArray<byte> instead of byte[]
                byte[] rawData = GetRawTextureDataSafe(texture);
                if (rawData == null || rawData.Length == 0)
                {
                    TranslatorCore.LogWarning("[CustomFontLoader] GetRawTextureData returned empty");
                    return;
                }

                // Determine bytes per pixel from format
                int bpp = GetBytesPerPixel(texture.format);
                if (bpp < 3)
                {
                    TranslatorCore.LogInfo($"[CustomFontLoader] Texture format {texture.format} (bpp={bpp}), skipping SDF conversion");
                    return;
                }

                int pixelCount = rawData.Length / bpp;
                bool needsConversion = false;

                // Sample check: if alpha is mostly max but R varies, we need to copy R to A
                int sampleCount = Math.Min(100, pixelCount);
                int alphaOnes = 0;
                int rVariation = 0;
                int lastR = -1;
                int alphaOffset = bpp >= 4 ? 3 : -1; // Alpha is 4th byte in RGBA32

                for (int i = 0; i < sampleCount; i++)
                {
                    int idx = (i * (pixelCount / sampleCount)) * bpp;
                    if (idx + bpp > rawData.Length) break;

                    byte r = rawData[idx]; // R is first byte
                    byte a = alphaOffset >= 0 ? rawData[idx + alphaOffset] : (byte)255;

                    if (a > 252) alphaOnes++;
                    if (lastR >= 0 && Math.Abs(r - lastR) > 2) rVariation++;
                    lastR = r;
                }

                needsConversion = alphaOnes > sampleCount * 0.9f && rVariation > sampleCount * 0.1f;

                if (needsConversion && alphaOffset >= 0)
                {
                    TranslatorCore.LogInfo("[CustomFontLoader] Converting SDF texture: copying R channel to Alpha");
                    for (int i = 0; i < pixelCount; i++)
                    {
                        int idx = i * bpp;
                        if (idx + bpp > rawData.Length) break;
                        byte r = rawData[idx];
                        rawData[idx] = 255;     // R = white
                        rawData[idx + 1] = 255; // G = white
                        rawData[idx + 2] = 255; // B = white
                        rawData[idx + alphaOffset] = r; // A = original R (SDF distance)
                    }
                    if (!LoadRawTextureDataSafe(texture, rawData))
                    {
                        TranslatorCore.LogWarning("[CustomFontLoader] Failed to write converted texture data back");
                        return;
                    }
                    texture.Apply();
                    TranslatorCore.LogInfo("[CustomFontLoader] SDF texture conversion complete");
                }
                else
                {
                    TranslatorCore.LogInfo("[CustomFontLoader] Texture appears to already have distance in Alpha channel");
                }
            }
            catch (Exception ex)
            {
                TranslatorCore.LogWarning($"[CustomFontLoader] Failed to convert SDF texture: {ex.Message}");
            }
        }

        /// <summary>
        /// Get raw texture data via reflection.
        /// On IL2CPP, GetRawTextureData() returns Il2CppStructArray&lt;byte&gt; instead of byte[].
        /// This method handles both cases.
        /// </summary>
        private static byte[] GetRawTextureDataSafe(Texture2D texture)
        {
            if (texture == null) return null;

            var type = texture.GetType();

            // Try all GetRawTextureData overloads via reflection
            foreach (var method in type.GetMethods(BindingFlags.Public | BindingFlags.Instance))
            {
                if (method.Name != "GetRawTextureData") continue;
                if (method.GetParameters().Length != 0) continue;
                if (method.IsGenericMethod) continue;

                try
                {
                    var result = method.Invoke(texture, null);
                    if (result == null) continue;

                    // Direct byte[] (Mono)
                    if (result is byte[] bytes)
                        return bytes;

                    // IL2CPP: result is Il2CppStructArray<byte> or similar
                    // It implements IEnumerable and has a Length property
                    var resultType = result.GetType();

                    // Try to get Length
                    var lengthProp = resultType.GetProperty("Length") ?? resultType.GetProperty("Count");
                    if (lengthProp == null) continue;

                    int length = (int)lengthProp.GetValue(result, null);
                    if (length == 0) continue;

                    // Try indexer access
                    var indexer = resultType.GetProperty("Item");
                    if (indexer != null)
                    {
                        byte[] data = new byte[length];
                        for (int i = 0; i < length; i++)
                        {
                            data[i] = (byte)indexer.GetValue(result, new object[] { i });
                        }
                        return data;
                    }

                    // Try as IList<byte> or IEnumerable
                    if (result is System.Collections.IEnumerable enumerable)
                    {
                        var list = new List<byte>();
                        foreach (var item in enumerable)
                        {
                            if (item is byte b)
                                list.Add(b);
                        }
                        if (list.Count > 0)
                            return list.ToArray();
                    }
                }
                catch (Exception ex)
                {
                    TranslatorCore.LogWarning($"[CustomFontLoader] GetRawTextureData reflection failed: {ex.Message}");
                }
            }

            return null;
        }

        /// <summary>
        /// Load raw texture data via reflection.
        /// On IL2CPP, LoadRawTextureData may expect Il2CppStructArray&lt;byte&gt; instead of byte[].
        /// </summary>
        private static bool LoadRawTextureDataSafe(Texture2D texture, byte[] data)
        {
            if (texture == null || data == null) return false;

            var type = texture.GetType();

            // Try direct call first (works on Mono)
            try
            {
                texture.LoadRawTextureData(data);
                return true;
            }
            catch { }

            // IL2CPP: try via reflection, find a LoadRawTextureData that accepts our data
            foreach (var method in type.GetMethods(BindingFlags.Public | BindingFlags.Instance))
            {
                if (method.Name != "LoadRawTextureData") continue;
                var parameters = method.GetParameters();
                if (parameters.Length != 1) continue;

                var paramType = parameters[0].ParameterType;

                // If it accepts byte[], call directly
                if (paramType == typeof(byte[]))
                {
                    try
                    {
                        method.Invoke(texture, new object[] { data });
                        return true;
                    }
                    catch { continue; }
                }

                // If it accepts Il2CppStructArray<byte> or similar, try to construct one
                try
                {
                    // Try to create an instance of the expected type from byte[]
                    var ctor = paramType.GetConstructor(new Type[] { typeof(byte[]) });
                    if (ctor != null)
                    {
                        var il2cppArray = ctor.Invoke(new object[] { data });
                        method.Invoke(texture, new object[] { il2cppArray });
                        return true;
                    }

                    // Try with int length constructor + copy
                    ctor = paramType.GetConstructor(new Type[] { typeof(int) });
                    if (ctor != null)
                    {
                        var il2cppArray = ctor.Invoke(new object[] { data.Length });
                        var indexer = paramType.GetProperty("Item");
                        if (indexer != null)
                        {
                            for (int i = 0; i < data.Length; i++)
                                indexer.SetValue(il2cppArray, data[i], new object[] { i });
                            method.Invoke(texture, new object[] { il2cppArray });
                            return true;
                        }
                    }
                }
                catch (Exception ex)
                {
                    TranslatorCore.LogWarning($"[CustomFontLoader] LoadRawTextureData IL2CPP conversion failed: {ex.Message}");
                }
            }

            return false;
        }

        /// <summary>
        /// Get bytes per pixel for a texture format.
        /// </summary>
        private static int GetBytesPerPixel(TextureFormat format)
        {
            switch (format)
            {
                case TextureFormat.RGBA32:
                case TextureFormat.BGRA32:
                case TextureFormat.ARGB32:
                    return 4;
                case TextureFormat.RGB24:
                    return 3;
                case TextureFormat.Alpha8:
                case TextureFormat.R8:
                    return 1;
                case TextureFormat.RG16:
                case TextureFormat.R16:
                    return 2;
                case TextureFormat.RGBAFloat:
                    return 16;
                case TextureFormat.RGBAHalf:
                    return 8;
                default:
                    return 4; // Assume RGBA32 as default
            }
        }
    }
}
